src/HomefinanceBundle/Rules/Actions/Form/AddTagForm.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */

namespace HomefinanceBundle\Rules\Actions\Form;

use HomefinanceBundle\Administration\Manager\TagManager;
use HomefinanceBundle\Rules\Actions\Form;
use Symfony\Component\Form\FormBuilderInterface;

class AddTagForm extends Form {

    /**
     * @var TagManager
     */
    protected $tagManager;

    public function __construct(TagManager $tagManager)
    {
        $this->tagManager = $tagManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tags', 'entity', array(
                'class' => 'HomefinanceBundle:Tag',
                'choices' => $this->tagManager->listAllTags(),
                'choice_label' => 'name',
                'label' => 'rules.action.add_tag.tags.label',
                'expanded' => true,
                'multiple' => true,
                'mapped' => false,
            ))
        ;

        parent::buildForm($builder, $options);
    }

    public function getName()
    {
        return 'rules_action_add_tag';
    }

}

src/HomefinanceBundle/Rules/Actions/Form/SetCategory.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */

namespace HomefinanceBundle\Rules\Actions\Form;

use HomefinanceBundle\Administration\Manager\CategoryManager;
use HomefinanceBundle\Rules\Actions\Form;
use Symfony\Component\Form\FormBuilderInterface;

class SetCategory extends Form {

    /**
     * @var CategoryManager
     */
    protected $categoryManager;

    public function __construct(CategoryManager $categoryManager)
    {
        $this->categoryManager = $categoryManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category', 'entity', array(
                'class' => 'HomefinanceBundle:Category',
                'choices' => $this->categoryManager->allLeafCategories(),
                'choice_label' => 'indentedTitle',
                'label' => 'rules.action.set_category.category.label',
                'empty_data'  => null,
                'empty_value' => "rules.action.set_category.category.empty",
                'mapped' => false,
            ))
        ;

        parent::buildForm($builder, $options);
    }

    public function getName()
    {
        return 'rules_action_set_category';
    }

}

src/HomefinanceBundle/Rules/Conditions/Form/CheckIban.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */
namespace HomefinanceBundle\Rules\Conditions\Form;

use HomefinanceBundle\Rules\Conditions\Form;
use Symfony\Component\Form\FormBuilderInterface;

class CheckIban extends Form
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('iban', 'text', array(
                'label' => 'rules.condition.check_iban.iban.label',
                'required' => true,
                'mapped' => false,
            ))
        ;

        parent::buildForm($builder, $options);
    }

    public function getName()
    {
        return 'rules_condition_check_iban';
    }

}

src/HomefinanceBundle/Rules/Conditions/Form/CheckNameForm.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */
namespace HomefinanceBundle\Rules\Conditions\Form;

use HomefinanceBundle\Rules\Conditions\Form;
use Symfony\Component\Form\FormBuilderInterface;

class CheckNameForm extends Form
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array(
                'label' => 'rules.condition.check_name.name.label',
                'required' => true,
                'mapped' => false,
            ))
        ;

        parent::buildForm($builder, $options);
    }

    public function getName()
    {
        return 'rules_condition_check_name';
    }

}

src/HomefinanceBundle/Rules/Conditions/Form/DescriptionContainsForm.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */
namespace HomefinanceBundle\Rules\Conditions\Form;

use HomefinanceBundle\Rules\Conditions\Form;
use Symfony\Component\Form\FormBuilderInterface;

class DescriptionContainsForm extends Form
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description', 'text', array(
                'label' => 'rules.condition.description_contains.description.label',
                'required' => true,
                'mapped' => false,
            ))
        ;

        parent::buildForm($builder, $options);
    }

    public function getName()
    {
        return 'rules_condition_description_contains_with';
    }

}

src/HomefinanceBundle/Rules/Conditions/Form/DescriptionStartsWithForm.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */
namespace HomefinanceBundle\Rules\Conditions\Form;

use HomefinanceBundle\Rules\Conditions\Form;
use Symfony\Component\Form\FormBuilderInterface;

class DescriptionStartsWithForm extends Form
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description', 'text', array(
                'label' => 'rules.condition.description_starts_with.description.label',
                'required' => true,
                'mapped' => false,
            ))
        ;

        parent::buildForm($builder, $options);
    }

    public function getName()
    {
        return 'rules_condition_description_starts_with';
    }

}

src/HomefinanceBundle/Rules/Form/ConditionForm.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */
namespace HomefinanceBundle\Rules\Form;

use HomefinanceBundle\Rules\Factory;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConditionForm extends AbstractType
{

    /**
     * @var Factory
     */
    protected $factory;

    public function __construct(Factory $factory)
    {
        $this->factory = $factory;
    }

    protected function getConditions() {
        $return = array();
        foreach($this->factory->getAllConditions() as $alias => $condition) {
            $return[$alias] = $condition->getName();
        }
        return $return;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('condition', 'choice', array(
                'label' => 'rules.condition.condition.label',
                'required' => true,
                'choices' => $this->getConditions(),
                'empty_data'  => null,
                'empty_value' => "rules.condition.condition.empty",
            ))
            ->add('actions', 'form_actions');

        $builder->get('actions')
            ->add('save', 'submit', array(
                'label' => 'rules.condition.update.btn-label',
                'attr' => array(
                    'class' => 'btn btn-lg btn-success',
                ),
            ))
        ;
    }

    public function getName()
    {
        return 'rules_condition';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'HomefinanceBundle\Entity\RuleCondition',
            'translation_domain' => 'rules',
        ));
    }

}

src/HomefinanceBundle/Rules/Controller/RulesController.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */

namespace HomefinanceBundle\Rules\Controller;

use HomefinanceBundle\DefaultController\DefaultController;
use HomefinanceBundle\Entity\Rule;
use HomefinanceBundle\Entity\RuleAction;
use HomefinanceBundle\Entity\RuleCondition;
use HomefinanceBundle\Share\Permission;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class RulesController extends DefaultController
{

    /**
     * @Route("/", name="rules")
     * @param Request $request
     * @return string
     */
    public function listRules(Request $request)
    {
        $administration = $this->checkCurrentAdministration(Permission::EDIT);

        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Rule');
        $rules = $repo->findByAdministration($administration);

        $factory = $this->get('homefinance.rules.factory');

        return $this->render('HomefinanceBundle:Rules:rules.html.twig', array(
            'administration' => $administration,
            'rules' => $rules,
            'factory' => $factory
        ));
    }

    /**
     * @Route("/add", name="add_rule")
     * @param Request $request
     * @return string
     */
    public function addRule(Request $request)
    {
        $administration = $this->checkCurrentAdministration(Permission::EDIT);

        $rule = new Rule();
        $rule->setAdministration($administration);
        $em = $this->getDoctrine()->getManager();
        $em->persist($rule);
        $em->flush();
        $this->addFlash('success', 'rule.added');

        return $this->redirect($this->generateUrl('add_condition', array('rule_id' => $rule->getId())));
    }

    /**
     * @Route("/{rule_id}/delete", name="delete_rule")
     *
     * @param Request $request
     * @param $rule_id
     * @return Response
     */
    public function deleteRule(Request $request, $rule_id) {
        $factory = $this->get('homefinance.rules.factory');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);
        $rule_repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Rule');
        $rule = $rule_repo->findOneByIdAndAdministration($administration, $rule_id);

        $em = $this->getDoctrine()->getManager();
        $em->remove($rule);
        $em->flush();
        $this->addFlash('success', 'rule.deleted');

        return $this->redirect($this->generateUrl('rules'));
    }

    /**
     * @Route("/{rule_id}/run", name="run_rule")
     *
     * @param Request $request
     * @param $rule_id
     * @return Response
     */
    public function runRules(Request $request, $rule_id) {
        $em = $this->getDoctrine()->getManager();
        $engine = $this->get('homefinance.rules.engine');
        $administration = $this->checkCurrentAdministration(Permission::VIEW);
        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Transaction');

        $transactions = $repo->findUnprocessedByAdministration($administration);

        $rule_repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Rule');
        $rule = $rule_repo->findOneByIdAndAdministration($administration, $rule_id);

        $transactions_processed = 0;
        foreach($transactions as $transaction) {
            if ($engine->triggerRule($transaction, $rule)) {
                $em->persist($transaction);
                $transactions_processed++;
            }
        }

        $this->addFlash('success', $this->get('translator')->trans('rule.executed', array('%count%' => $transactions_processed)));
        $em->flush();
        return $this->redirect($this->generateUrl('rules'));
    }

    /**
     * @Route("/{rule_id}/add_condition", name="add_condition")
     *
     * @param Request $request
     * @param $rule_id
     * @return Response
     */
    public function addCondition(Request $request, $rule_id) {
        $factory = $this->get('homefinance.rules.factory');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);
        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Rule');
        $rule = $repo->findOneByIdAndAdministration($administration, $rule_id);
        $condition = new RuleCondition();
        $condition->setRule($rule);

        $form = $this->createForm('rules_condition', $condition);
        $form->get('actions')->add('save_add_condition', 'submit', array(
            'label' => 'rules.condition.save_add_condition.btn-label',
            'attr' => array(
                'class' => 'btn btn-lg btn-primary',
            ),
        ));
        $form->get('actions')->add('save_add_action', 'submit', array(
            'label' => 'rules.condition.save_add_action.btn-label',
            'attr' => array(
                'class' => 'btn btn-lg btn-warning',
            ),
        ));
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($condition);
            $em->flush();
            $this->addFlash('success', 'condition.edited');

            if ($factory->hasConditionForm($condition)) {
                $params = array(
                    'rule_id' => $rule_id,
                    'condition_id' => $condition->getId(),
                );
                if ($form->get('actions')->get('save_add_condition')->isClicked()) {
                    $params['next'] = 'condition';
                } elseif ($form->get('actions')->get('save_add_action')->isClicked()) {
                    $params['next'] = 'action';
                }
                return $this->redirect($this->generateUrl('edit_condition', $params));
            } elseif ($form->get('actions')->get('save_add_condition')->isClicked()) {
                return $this->redirect($this->generateUrl('add_condition', array('rule_id' => $rule_id)));
            } elseif ($form->get('actions')->get('save_add_action')->isClicked()) {
                return $this->redirect($this->generateUrl('add_action', array('rule_id' => $rule_id)));
            }
            return $this->redirect($this->generateUrl('rules'));
        }

        return $this->render('HomefinanceBundle:Rules:add_condition.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/{rule_id}/delete_condition/{condition_id}", name="delete_condition")
     *
     * @param Request $request
     * @param $rule_id
     * @param $condition_id
     * @return Response
     */
    public function deleteCondition(Request $request, $rule_id, $condition_id) {
        $factory = $this->get('homefinance.rules.factory');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);
        $rule_repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Rule');
        $rule = $rule_repo->findOneByIdAndAdministration($administration, $rule_id);

        $condition_repo = $this->getDoctrine()->getRepository('HomefinanceBundle:RuleCondition');
        $condition = $condition_repo->findOneBy(array('id' => $condition_id));

        $em = $this->getDoctrine()->getManager();
        $em->remove($condition);
        $em->flush();
        $this->addFlash('success', 'condition.deleted');

        return $this->redirect($this->generateUrl('rules'));
    }

    /**
     * @Route("/{rule_id}/edit_condition/{condition_id}/{next}", defaults={"next"=null}, name="edit_condition")
     *
     * @param Request $request
     * @param $rule_id
     * @param $condition_id
     * @param $next
     * @return Response
     */
    public function editCondition(Request $request, $rule_id, $condition_id, $next=null) {
        $factory = $this->get('homefinance.rules.factory');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);
        $rule_repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Rule');
        $rule = $rule_repo->findOneByIdAndAdministration($administration, $rule_id);

        $condition_repo = $this->getDoctrine()->getRepository('HomefinanceBundle:RuleCondition');
        $condition = $condition_repo->findOneBy(array('id' => $condition_id));
        $class = $factory->getConditionClass($condition->getCondition());
        $form = $this->createForm($class->getForm($condition), $condition);
        $class->setFormData($form, $condition);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $class->formIsSubmitted($form, $condition);
            $em = $this->getDoctrine()->getManager();
            $em->persist($condition);
            $em->flush();
            $this->addFlash('success', 'condition.edited');

            if ($next == 'condition') {
                return $this->redirect($this->generateUrl('add_condition', array('rule_id' => $rule_id)));
            } elseif ($next == 'action') {
                return $this->redirect($this->generateUrl('add_action', array('rule_id' => $rule_id)));
            }

            return $this->redirect($this->generateUrl('rules'));
        }

        return $this->render('HomefinanceBundle:Rules:edit_condition.html.twig', array(
            'form' => $form->createView(),
            'factory' => $factory,
            'condition' => $condition,
        ));
    }

    /**
     * @Route("/{rule_id}/add_action", name="add_action")
     *
     * @param Request $request
     * @param $rule_id
     * @return Response
     */
    public function addAction(Request $request, $rule_id) {
        $factory = $this->get('homefinance.rules.factory');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);
        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Rule');
        $rule = $repo->findOneByIdAndAdministration($administration, $rule_id);
        $action = new RuleAction();
        $action->setRule($rule);

        $form = $this->createForm('rules_action', $action);

src/HomefinanceBundle/Resources/views/Rules/add_action.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "rules" %}

{% block title %}
    {{ 'rules.add_action.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'rules.add_action.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Rules/add_condition.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "rules" %}

{% block title %}
    {{ 'rules.add_condition.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'rules.add_condition.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Rules/edit_action.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "rules" %}

{% block title %}
    {{ 'rules.edit_action.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'rules.edit_action.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Rules/edit_condition.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "rules" %}

{% block title %}
    {{ 'rules.edit_condition.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'rules.edit_condition.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Rules/rules.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "rules" %}

{% block title %}
    {{ 'manage_rules.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'manage_rules.title'|trans }}
{% endblock %}

{% block form %}

    {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
        <div class="margin-bottom">
        <a class="btn btn-success" href="{{ url('add_rule') }}" role="button"><i class="glyphicon glyphicon-plus"></i> {{ 'rule.add'|trans() }}</a>
        </div>
    {% endif %}

    {% for rule in rules %}
        {% if (loop.first or (loop.index % 3) == 1) %}
            <div class="row">
        {% endif %}
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    {{ 'rule'|trans() }}
                    <span class="pull-right">
                    {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
                        <a class="btn btn-success btn-xs" role="button" href="{{ url('run_rule', {'rule_id': rule.id}) }}" title="{{ 'rule.run'|trans }}"><i class="glyphicon glyphicon-triangle-right"></i></a>
                        <a class="btn btn-danger btn-xs" role="button" href="{{ url('delete_rule', {'rule_id': rule.id}) }}" title="{{ 'rule.delete'|trans() }}" onclick="return confirm('{{ 'rule.delete_confirm'|trans }}');"><i class="glyphicon glyphicon-trash"></i></a>
                    {% endif %}
                </div>
                <div class="panel-body">
                    <div class="panel panel-default">
                        <div class="panel-heading">{{ 'rule.conditions'|trans() }}</div>
                        <div class="panel-body">
                            {% for condition in rule.conditions %}
                                <p>{{ factory.getConditionLabel(condition) }}
                                <span class="pull-right">
                                {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
                                    {% if (factory.hasConditionForm(condition)) %}
                                    <a class="btn btn-default btn-xs" role="button" href="{{ url('edit_condition', {'rule_id': rule.id, 'condition_id': condition.id}) }}" title="{{ 'rule.condition.edit'|trans() }}"><i class="glyphicon glyphicon-pencil"></i></a>
                                    {% endif %}
                                    <a class="btn btn-danger btn-xs" role="button" href="{{ url('delete_condition', {'rule_id': rule.id, 'condition_id': condition.id}) }}" title="{{ 'rule.condition.delete'|trans() }}" onclick="return confirm('{{ 'rule.condition.delete_confirm'|trans }}');"><i class="glyphicon glyphicon-trash"></i></a>
                                {% endif %}
                                </span>
                                </p>
                            {% endfor %}
                            {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
                                <a class="btn btn-success btn-xs" role="button" href="{{ url('add_condition', {rule_id: rule.id}) }}">
                                    <i class="glyphicon glyphicon-plus"></i> {{ 'rule.add_condition'|trans() }}
                                </a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">{{ 'rule.actions'|trans() }}</div>
                        <div class="panel-body">
                            {% for rule_action in rule.actions %}
                                <p>{{ factory.getActionLabel(rule_action) }}
                                <span class="pull-right">
                                {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
                                    {% if (factory.hasActionForm(rule_action)) %}
                                    <a class="btn btn-default btn-xs" role="button" href="{{ url('edit_action', {'rule_id': rule.id, 'action_id': rule_action.id}) }}" title="{{ 'rule.action.edit'|trans() }}"><i class="glyphicon glyphicon-pencil"></i></a>
                                    {%  endif %}
                                    <a class="btn btn-danger btn-xs" role="button" href="{{ url('delete_action', {'rule_id': rule.id, 'action_id': rule_action.id}) }}" title="{{ 'rule.action.delete'|trans() }}" onclick="return confirm('{{ 'rule.action.delete_confirm'|trans }}');"><i class="glyphicon glyphicon-trash"></i></a>
                                {% endif %}
                                </span>
                                </p>
                            {% endfor %}

                            {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
                                <a class="btn btn-success btn-xs" role="button" href="{{ url('add_action', {rule_id: rule.id}) }}">
                                    <i class="glyphicon glyphicon-plus"></i> {{ 'rule.add_action'|trans() }}
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if (loop.last or (loop.index % 3) == 0) %}
            </div>
        {% endif %}
    {% endfor %}

    {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
        <a class="btn btn-success" href="{{ url('add_rule') }}" role="button"><i class="glyphicon glyphicon-plus"></i> {{ 'rule.add'|trans() }}</a>
    {% endif %}
{% endblock %}