src/HomefinanceBundle/Entity/User.php
<?php

namespace HomefinanceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use HomefinanceBundle\User\Entity\User as BaseUser;

/**
 * User
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class User extends BaseUser
{

}

src/HomefinanceBundle/User/Entity/User.php
<?php

namespace HomefinanceBundle\User\Entity;

use Doctrine\ORM\Mapping as ORM;
use HomefinanceBundle\Entity\Administration;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * @MappedSuperclass
 */
abstract class User implements AdvancedUserInterface
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255, nullable=true)
     */
    protected $password;

    /**
     * @var string
     *
     * @ORM\Column(name="salt", type="string", length=32)
     */
    protected $salt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="lastlogin", type="datetime", nullable=true)
     */
    protected $lastlogin;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="password_requested_at", type="datetime", nullable=true)
     */
    protected $passwordRequestedAt;

    /**
     * @var string
     *
     * @ORM\Column(name="confirmation_token", type="string", length=128, nullable=true)
     */
    protected $confirmationToken;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="confirmation_requested_at", type="datetime", nullable=true)
     */
    protected $confirmationRequestedAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="confirmation_token_valid_till", type="datetime", nullable=true)
     */
    protected $confirmationTokenValidTill;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     */
    protected $email;

    /**
     * @var string
     *
     * @ORM\Column(name="new_email", type="string", length=255, nullable=true)
     */
    protected $newEmail;

    /**
     * @var boolean
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    protected $enabled;

    /**
     * @var boolean
     *
     * @ORM\Column(name="locked", type="boolean")
     */
    protected $locked;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    protected $avatar;

    /**
     * @var array
     */
    protected $roles;

    /**
     * @var Administration
     *
     * @ORM\ManyToOne(targetEntity="Administration")
     * @ORM\JoinColumn(name="current_administration_id", referencedColumnName="id", onDelete="SET NULL", nullable=true)
     */
    protected $current_administration;


    public function __construct() {
        $this->salt = base_convert(sha1(uniqid(mt_rand(), true)), 16, 36);
        $this->enabled = false;
        $this->locked = false;
        $this->roles = array();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * @return string
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * @param $email
     * @return User
     */
    public function setEmail($email) {
        $this->email = $email;
        return $this;
    }

    /**
     * @return string
     */
    public function getNewEmail() {
        return $this->newEmail;
    }

    /**
     * @param $email
     * @return User
     */
    public function setNewEmail($email=null) {
        $this->newEmail = $email;
        return $this;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    public function isAccountNonExpired() {
        return true;
    }

    public function isAccountNonLocked() {
        if ($this->locked) {
            return false;
        }
        return true;
    }

    public function isCredentialsNonExpired() {
        return true;
    }

    public function isEnabled() {
        if ($this->enabled) {
            return true;
        }
        return false;
    }

    /**
     * @param bool $enabled
     * @return User
     */
    public function setEnabled($enabled) {
        $this->enabled = $enabled ? true : false;
        return $this;
    }

    public function getRoles() {
        return explode(",", $this->roles);
    }

    public function setRoles($roles) {
        if (is_array($roles)) {
            $this->roles = implode(",", $roles);
        } else {
            $this->roles = $roles;
        }
    }

    /**
     * @return string
     */
    public function getSalt() {
        return $this->salt;
    }

    public function eraseCredentials() {
    }

    /**
     * @return \DateTime
     */
    public function getPasswordRequestedAt() {
        return $this->passwordRequestedAt;
    }

    /**
     * @param \DateTime $datetime
     * @return User
     */
    public function setPasswordRequestedAt(\DateTime $datetime=null) {
        $this->passwordRequestedAt = $datetime;
        return $this;
    }

    /**
     * @return string
     */
    public function getConfirmationToken() {
        return $this->confirmationToken;
    }

    /**
     * @param $token
     * @return User
     */
    public function setConfirmationToken($token=null) {
        $this->confirmationToken = $token;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getConfirmationRequestedAt() {
        return $this->confirmationRequestedAt;
    }

    /**
     * @param \DateTime $requestDate
     * @return User
     */
    public function setConfirmationRequestedAt(\DateTime $requestDate=null) {
        $this->confirmationRequestedAt = $requestDate;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getConfirmationTokenValidTill() {
        return $this->confirmationTokenValidTill;
    }

    public function setConfirmationTokenValidTill(\DateTime $tokenValidTill=null) {
        $this->confirmationTokenValidTill = $tokenValidTill;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getLastlogin() {
        return $this->lastlogin;
    }

    /**
     * @param \DateTime $lastlogin_datetime
     * @return User
     */
    public function setLastlogin(\DateTime $lastlogin_datetime) {
        $this->lastlogin = $lastlogin_datetime;
        return $this;
    }

    /**
     * @return string
     */
    public function getName() {
        return !empty($this->name) ? $this->name : $this->getUsername();
    }

    public function isTokenValid() {
        if (empty($this->confirmationToken)) {
            return false;
        }

        if (empty($this->confirmationTokenValidTill)) {
            return false;
        }

        $today = new \DateTime();
        if ($this->confirmationTokenValidTill <= $today) {
            return false;
        }

        return true;
    }

    /**
     * @param string $name
     * @return User
     */
    public function setName($name) {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getAvatar() {
        if (empty($this->avatar)) {
            return $this->getDefaultAvatar();
        }
        return $this->avatar;
    }

    public function getDefaultAvatar() {
        return 'bundles/homefinance/images/avatar/default.png';
    }

    public function hasAvatar() {
        if (empty($this->avatar)) {
            return false;
        }
        return true;
    }

    /**
     * @return Administration
     */
    public function getCurrentAdministration() {
        return $this->current_administration;
    }

    /**
     * @param Administration|null $administration
     * @return User
     */
    public function setCurrentAdministration(Administration $administration=null) {
        $this->current_administration = $administration;
        return $this;
    }

    /**
     * @param $avatar
     * @return User
     */
    public function setAvatar($avatar=null) {
        $this->avatar = $avatar;
        return $this;
    }

    public function __toString()
    {
        return (string) $this->getUsername();
    }
}

src/HomefinanceBundle/User/Form/ChangePasswordType.php
<?php

namespace HomefinanceBundle\User\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChangePasswordType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('currentPassword', 'password', array(
            'label' => 'user.your_current_password'
        ));
        $builder->add('newPassword', 'repeated', array(
            'type' => 'password',
            'invalid_message' => 'user.password.invalid-message',
            'options' => array('attr' => array('class' => 'password-field')),
            'first_options'  => array('label' => 'user.password.label1'),
            'second_options' => array('label' => 'user.password.label2'),
        ));
        $builder->add('save', 'submit', array(
            'label' => 'change_password.update.btn-label',
            'attr' => array(
                'class' => 'btn btn-lg btn-primary',
            ),
        ));
    }

    public function getName()
    {
        return 'change_password';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'HomefinanceBundle\User\Model\ChangePassword',
            'translation_domain' => 'user',
        ));
    }
}

src/HomefinanceBundle/User/Form/ConfirmationType.php
<?php

namespace HomefinanceBundle\User\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConfirmationType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('confirmationToken', 'text', array(
            'label' => 'confirmation.token.label',
            'attr' => array(
                'placeholder' => 'confirmation.token.placeholder',
                'help_text' => 'confirmation.token.help_text'
            ),
        ));
        $builder->add('save', 'submit', array(
            'label' => 'confirmation.confirm.btn-label',
            'attr' => array(
                'class' => 'btn btn-lg btn-primary',
            ),
        ));
    }

    public function getName()
    {
        return 'confirmation';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'HomefinanceBundle\User\Model\Confirmation',
            'translation_domain' => 'user',
        ));
    }
}

src/HomefinanceBundle/User/Form/LostPasswordType.php
<?php

namespace HomefinanceBundle\User\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LostPasswordType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('email', 'email', array(
            'label' => 'lost_password.email.label',
        ));
        $builder->add('save', 'submit', array(
            'label' => 'lost_password.confirm.btn-label',
            'attr' => array(
                'class' => 'btn btn-lg btn-primary',
            ),
        ));
    }

    public function getName()
    {
        return 'lost_password';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'HomefinanceBundle\User\Model\LostPassword',
            'translation_domain' => 'user',
        ));
    }
}

src/HomefinanceBundle/User/Controller/ProfileController.php
<?php

namespace HomefinanceBundle\User\Controller;


use HomefinanceBundle\User\Model\ChangePassword;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use HomefinanceBundle\User\Model\Profile;
use Symfony\Component\Validator\Constraints\Image;


class ProfileController extends Controller {

    /**
     * @route("/profile", name="profile")
     * @param Request $request
     * @return Response
     */
    public function userProfileAction(Request $request) {
        $factory = $this->get('homefinance.user.factory');
        $manager = $this->get('homefinance.user.manager');

        $user = $this->getUser();

        $profile = $factory->getProfile($user);
        $form = $this->createForm('profile', $profile);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $manager->updateProfile($profile, $user);
            $this->addFlash('success', 'user.profile.updated');
        }

        if (!empty($this->getUser()->getNewEmail())) {
            $this->addFlash('info', 'user.profile.email_cofirmation_waiting');
        }

        return $this->render('HomefinanceBundle:user:profile.html.twig', array(
            'form' => $form->createView(),
            'user' => $user,
        ));
    }

    /**
     * @route("/profile/change-avatar", name="change-avatar")
     * @param Request $request
     * @return Response
     */
    public function uploadAvatarAction(Request $request) {
        $user = $this->getUser();
        $formBuilder = $this->createFormBuilder();
        $formBuilder->add('avatar', 'file', array(
            'label' => $this->get('translator')->trans('change-avatar.file', array(), 'user'),
            'required' => false,
            'mapped' => false,
            'constraints' => array(
                new Image(),
            )
        ));
        $formBuilder->add('submit', 'submit', array(
            'label' => $this->get('translator')->trans('change-avatar.upload', array(), 'user'),
            'attr' => array(
                'class' => 'btn btn-lg btn-primary',
            ),
        ));
        $removeVisibleClass = '';
        if (!$user->hasAvatar()) {
            $removeVisibleClass = 'hidden';
        }
        $formBuilder->add('remove', 'button', array(
            'label' => $this->get('translator')->trans('change-avatar.remove', array(), 'user'),
            'attr' => array(
                'class' => 'btn btn-sm btn-danger remove '.$removeVisibleClass,
            ),
        ));

        $form = $formBuilder->getForm();
        $form->handleRequest($request);
        if ($form->isValid()) {
            $avatar = $form['avatar']->getData();
            $dir = $this->get('kernel')->getRootDir() . '/../web/';
            $dir = realpath($dir);
            if ($user->hasAvatar() && file_exists($dir.'/'.$user->getAvatar())) {
                unlink($dir.'/'.$user->getAvatar());
            }
            $user->setAvatar(null);

            if ($form->getClickedButton()->getName() == 'submit' && !empty($avatar)) {
                $filename = sha1(uniqid($user->getId(), true)).'.'.$avatar->guessExtension();
                $avatar->move($dir . '/avatars', $filename);
                $user->setAvatar('avatars/' . $filename);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirect($this->generateUrl('profile'));
        }

        return $this->render('HomefinanceBundle:user:avatar.html.twig', array(
            'form' => $form->createView(),
            'user' => $user,
        ));
    }

    /**
     * @route("/profile/change_password", name="profile_change_password")
     * @param Request $request
     * @return Response
     */
    public function changePasswordAction(Request $request) {
        $factory = $this->get('homefinance.user.factory');
        $manager = $this->get('homefinance.user.manager');

        $profile = $factory->getChangePassword($this->getUser());
        $form = $this->createForm('change_password', $profile);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $manager->changePassword($profile);
            $this->addFlash('success', 'change_password.updated');
        }

        return $this->render('HomefinanceBundle:user:change_password.html.twig', array(
            'form' => $form->createView(),
        ));
    }

}

src/HomefinanceBundle/Resources/views/user/avatar.html.twig
{% extends 'HomefinanceBundle:layout:account_settings.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'change-avatar.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'change-avatar.title'|trans }}
{% endblock %}

{% block form %}
    {{ form_start(form) }}
    <div class="row">
    <div class="col-md-2">
        <div class="profile-picture-big">
        <img id="avatar_preview" src="{{ user.avatar|imagine_filter('big_profile_picture') }}" alt="{{ user.name }}" class="img-responsive" />
        {{ form_widget(form.remove) }}
        </div>
    </div>
    <div class="col-md-4">
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
<script type="text/javascript">
    $(function() {
        $("#form_avatar").change(function(){
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#avatar_preview').attr('src', e.target.result);
                    $('#avatar_preview').addClass('preview');
                    $('#form_remove').removeClass('hidden');
                }

                reader.readAsDataURL(this.files[0]);
            }
        });

        $('#form_remove').click(function() {
            $('#avatar_preview').attr('src', '{{ user.defaultAvatar|imagine_filter('big_profile_picture') }}');
            $('#form_avatar').files = new Array();
            $('#form_remove').addClass('hidden');
        });
    });
</script>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/change_password.html.twig
{% extends 'HomefinanceBundle:layout:account_settings.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'change_password.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'change_password.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/user/confirmation.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'confirmation.title'|trans }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <legend><h2>{{ 'confirmation.title'|trans }}</h2></legend>
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/HomefinanceBundle/Resources/views/user/confirmation_success.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'confirmation.success.title'|trans }}
{% endblock %}

{% block content %}
    <h2>{{ 'confirmation.success.title'|trans }}</h2>
    <p>{{ 'confirmation.success.body'|trans({'%login_link%': url('login')})|raw|nl2br }}</p>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/login.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'login.title'|trans }}
{% endblock %}

{% block content %}
<form class="form-basic" method='post' action='{{path('login_check')}}'>
    <h2>{{ 'login.title'|trans }}</h2>
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'user') }}</div>
    {% endif %}
    <div class="form-group">
        <input type="text" id="inputName" class="form-control" name='_username' placeholder="{{ 'login.email.placeholder'|trans }}" required autofocus value="{{ last_username }}">
    </div>
    <div class="form-group">
        <input type="password" id="inputPassword" class="form-control" name="_password" placeholder="{{ 'login.password.placeholder'|trans }}" required>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label>
                <input type="checkbox" name="_remember_me" id="remember_me">{{ 'login.remember-me'|trans }}
            </label>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-lg" type="submit">{{ 'login.login-btn-label'|trans }}</button>
        <a href="{{ url('lost_password') }}">{{  'lost_password.link_title'|trans }}</a>
    </div>

    <p>{{  'login.dont-have-an-account'|trans({'%registration_link%': path('registration')})|raw }}</p>

</form>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/lost_password.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'lost_password.title'|trans }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <legend><h2>{{ 'lost_password.title'|trans }}</h2></legend>
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/HomefinanceBundle/Resources/views/user/lost_password_success.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'lost_password.title'|trans }}
{% endblock %}

{% block content %}
    <h2>{{ 'lost_password.title'|trans }}</h2>
    <p>{{ 'lost_password.success_message'|trans({'%login_link%': url('login')})|raw|nl2br }}</p>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/new_account_confirmation.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'new_account_confirmation.title'|trans }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <legend><h2>{{ 'new_account_confirmation.title'|trans }}</h2></legend>
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/HomefinanceBundle/Resources/views/user/profile.html.twig
{% extends 'HomefinanceBundle:layout:account_settings.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'profile.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'profile.title'|trans }}
{% endblock %}

{% block form %}
    <div class="row">
    <div class="col-md-2">
        <a class="profile-picture-big" href="{{ url('change-avatar') }}">
        <img src="{{ user.avatar|imagine_filter('big_profile_picture') }}" alt="{{ user.name }}" class="img-responsive" />
        <i class="glyphicon glyphicon-pencil pull-right edit"></i>
        </a>
    </div>
    <div class="col-md-4">
        {{ parent() }}
    </div>
    </div>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/registration.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'registration.create-an-account.title'|trans }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <legend><h2>{{ 'registration.create-an-account.title'|trans }}</h2></legend>
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    <p>
        {{ 'registration.create-an-account.already-have-an-account'|trans({'%login_link%': path('login')})|raw }}
    </p>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
<script type="text/javascript">
    var custom_administration_name = false;
    var current_administration_name = '';

    $(function() {
        $('#registration_name').change(copyName);
        $('#registration_name').keyup(copyName);

        $('#registration_administration_name').change(checkCustom);
        $('#registration_administration_name').keyup(checkCustom);
    });


    function copyName() {
        if (custom_administration_name) {
            return;
        }
        $('#registration_administration_name').val($('#registration_name').val());
        current_administration_name = $('#registration_administration_name').val();
    }

    function checkCustom() {
        if (current_administration_name != $('#registration_administration_name').val()) {
            custom_administration_name = true;
        } else {
            custom_administration_name = false;
        }
    }

</script>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/registration_success.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'registration.success.title'|trans }}
{% endblock %}

{% block content %}
    <h2>{{ 'registration.success.title'|trans }}</h2>
    <p>{{ 'registration.success.body'|trans|nl2br }}</p>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/reset_password.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'reset_password.title'|trans }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <legend><h2>{{ 'reset_password.title'|trans }}</h2></legend>
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/HomefinanceBundle/Resources/views/user/reset_password_success.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'reset_password.success.title'|trans }}
{% endblock %}

{% block content %}
    <h2>{{ 'reset_password.success.title'|trans }}</h2>
    <p>{{ 'reset_password.success.body'|trans({'%login_link%': url('login')})|raw|nl2br }}</p>
{% endblock %}

src/HomefinanceBundle/Resources/views/user/reset_password_token.html.twig
{% extends 'HomefinanceBundle:layout:small_form.html.twig' %}

{% trans_default_domain "user" %}

{% block title %}
    {{ 'reset_password.title'|trans }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <legend><h2>{{ 'reset_password.title'|trans }}</h2></legend>
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}