src/HomefinanceBundle/Entity/Category.php
<?php

namespace HomefinanceBundle\Entity;

use HomefinanceBundle\Category\Exception\InvalidCategoryTypeException;
use HomefinanceBundle\Category\Type;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @Gedmo\Tree(type="nested")
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="HomefinanceBundle\Entity\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(length=64)
     */
    private $title;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(length=64)
     */
    private $type;

    /**
     * @var Administration
     *
     * @Assert\NotNull()
     * @ORM\ManyToOne(targetEntity="Administration")
     * @ORM\JoinColumn(name="administration_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $administration;

    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"type", "title"})
     * @ORM\Column(length=64, unique=true)
     */
    private $slug;

    /**
     * @var int
     *
     * @Gedmo\TreeLeft
     * @ORM\Column(type="integer")
     */
    private $lft;

    /**
     * @var int
     *
     * @Gedmo\TreeRight
     * @ORM\Column(type="integer")
     */
    private $rgt;

    /**
     * @var Category
     *
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * @var int
     *
     * @Gedmo\TreeRoot
     * @ORM\Column(type="integer", nullable=true)
     */
    private $root;

    /**
     * @var int
     *
     * @Gedmo\TreeLevel
     * @ORM\Column(name="lvl", type="integer")
     */
    private $level;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Category", mappedBy="parent", cascade={"persist"})
     */
    private $children;

    public function __construct() {
        $this->children = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getSlug() {
        return $this->slug;
    }

    public function getIndentedTitle() {
        $title = '';
        if ($this->parent && $this->parent->getLevel() > 0) {
            $title = $this->parent->getIndentedTitle();
        }
        if (strlen($title)) {
            $title = '  '.$title.': ';
        }
        return $title.$this->title;
    }

    /**
     * @return string
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * @param string $title
     * @return Cateory
     */
    public function setTitle($title) {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getType() {
        return $this->type;
    }

    /**
     * @param $type
     * @return $this
     * @throws InvalidCategoryTypeException
     */
    public function setType($type) {
        if (!Type::isTypeValid($type)) {
            throw new InvalidCategoryTypeException();
        }
        $this->type = $type;
        return $this;
    }

    /**
     * @param Category $parent
     * @return Category
     */
    public function setParent(Category $parent)
    {
        $this->parent = $parent;
        return $this;
    }

    /**
     * @return Category
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @return int
     */
    public function getRoot()
    {
        return $this->root;
    }

    /**
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * @return ArrayCollection
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * @return int
     */
    public function getLeft()
    {
        return $this->lft;
    }

    /**
     * @return int
     */
    public function getRight()
    {
        return $this->rgt;
    }

    /**
     * @return Administration
     */
    public function getAdministration() {
        return $this->administration;
    }

    /**
     * @param Administration $administration
     * @return Category
     */
    public function setAdministration(Administration $administration) {
        $this->administration = $administration;
        return $this;
    }

    public function isDirectSubOfRoot() {
        if ($this->parent) {
            if ($this->parent->getType() == Type::ROOT) {
                return true;
            }
        }
        return false;
    }

    public function isFirstSibling() {
        if (($this->getLeft() - 1) == $this->parent->getLeft()) {
            return true;
        }
        return false;
    }

    public function isLastSibling() {
        if (($this->getRight() +1) == $this->parent->getRight()) {
            return true;
        }
        return false;
    }

    public function __toString() {
        return $this->getIndentedTitle();
    }
}

src/HomefinanceBundle/Administration/Controller/TransactionController.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */

namespace HomefinanceBundle\Administration\Controller;

use HomefinanceBundle\DefaultController\DefaultController;
use HomefinanceBundle\Entity\Administration;
use HomefinanceBundle\Entity\Transaction;
use HomefinanceBundle\Filters\Model\FilterData;
use HomefinanceBundle\Share\Permission;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class TransactionController extends DefaultController {

    /**
     * @Route("/transactions/unprocessed{filter}/{value}", defaults={"filter"=null,"value"=null}, name="list_unprocessed_transactions")
     * @param Request $request
     * @return string
     */
    public function listUnprocessedAction(Request $request,$filter=null, $value=null) {
        $administration = $this->checkCurrentAdministration(Permission::VIEW);
        $filterFactory = $this->get('homefinance.filter_factory');
        $filterBag = $this->get('homefinance.filter_bag');
        $filterObject = $filterBag->get('unprocessed_transactions');
        if ($filter !== null) {
            $filterObject->set($filter, $value);
        }
        $filterObject->set('year', null);
        $filterBag->set('unprocessed_transactions', $filterObject);
        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Transaction');

        $transactions = $repo->findUnprocessedByAdministrationAndFilter($administration, $filterObject);

        return $this->render('HomefinanceBundle:Transaction:list.html.twig', array(
            'transactions' => $transactions,
            'administration' => $administration,
            'title' => $this->get('translator')->trans('transactions.list.unprocessed.title', array(), 'administration'),
            'filter' => $filterObject,
            'filterFactory' => $filterFactory,
            'showProcessedFilter' => false,
            'page' => 'list_unprocessed_transactions',
            'yearFilter' => false,
        ));
    }

    /**
     * @Route("/transactions/all/{filter}/{value}/{filter2}/{value2}", defaults={"filter"=null,"value"=null, "filter2"=null,"value2"=null}, name="list_all_transactions")
     * @param Request $request
     * @param $filter
     * @param $value
     * @param $filter2
     * @param $value2
     * @return string
     */
    public function listAllTransactions(Request $request, $filter=null, $value=null,$filter2=null,$value2=null) {
        $administration = $this->checkCurrentAdministration(Permission::VIEW);
        $filterFactory = $this->get('homefinance.filter_factory');
        $filterBag = $this->get('homefinance.filter_bag');
        $filterObject = $filterBag->get('all_transactions');
        if ($filter !== null) {
            $filterObject->set($filter, $value);
        }
        if ($filter2 != null) {
            $filterObject->set($filter2, $value2);
        }
        $filterBag->set('all_transactions', $filterObject);

        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Transaction');
        $transactions = $repo->findByAdministrationAndFilter($administration, $filterObject);

        return $this->render('HomefinanceBundle:Transaction:list.html.twig', array(
            'transactions' => $transactions,
            'administration' => $administration,
            'title' => $this->get('translator')->trans('transactions.list.all.title', array(), 'administration'),
            'page' => 'list_all_transactions',
            'filter' => $filterObject,
            'filterFactory' => $filterFactory,
            'showProcessedFilter' => true,
            'yearFilter' => true,
        ));
    }

    /**
     * @Route("/transactions/all_by_tag/{filter}/{value}/{filter2}/{value2}/{reset}", defaults={"filter"=null,"value"=null, "filter2"=null,"value2"=null, "reset"=false}, name="list_all_transactions_by_tag")
     * @param Request $request
     * @param $filter
     * @param $value
     * @param $filter2
     * @param $value2
     * @return string
     */
    public function listAllTransactionsByTag(Request $request, $filter=null, $value=null,$filter2=null,$value2=null,$reset=false) {
        $administration = $this->checkCurrentAdministration(Permission::VIEW);
        $filterFactory = $this->get('homefinance.filter_factory');
        $filterBag = $this->get('homefinance.filter_bag');
        $filterObject = $filterBag->get('all_transactions_by_tag', $reset);
        if ($filter !== null) {
            $filterObject->set($filter, $value);
        }
        if ($filter2 != null) {
            $filterObject->set($filter2, $value2);
        }
        $filterBag->set('all_transactions', $filterObject);

        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Transaction');
        $transactions = $repo->findByAdministrationAndFilter($administration, $filterObject);

        return $this->render('HomefinanceBundle:Transaction:list.html.twig', array(
            'transactions' => $transactions,
            'administration' => $administration,
            'title' => $this->get('translator')->trans('transactions.list.all.title', array(), 'administration'),
            'page' => 'list_all_transactions_by_tag',
            'filter' => $filterObject,
            'filterFactory' => $filterFactory,
            'showProcessedFilter' => true,
            'yearFilter' => true,
        ));
    }

    /**
     * @Route("/transactions/all_by_category/{filter}/{value}/{filter2}/{value2}/{reset}", defaults={"filter"=null,"value"=null, "filter2"=null,"value2"=null, "reset"=false}, name="list_all_transactions_by_category")
     * @param Request $request
     * @param $filter
     * @param $value
     * @param $filter2
     * @param $value2
     * @return string
     */
    public function listAllTransactionsByCategory(Request $request, $filter=null, $value=null,$filter2=null,$value2=null,$reset=false) {
        $administration = $this->checkCurrentAdministration(Permission::VIEW);
        $filterFactory = $this->get('homefinance.filter_factory');
        $filterBag = $this->get('homefinance.filter_bag');
        $filterObject = $filterBag->get('all_transactions_by_category', $reset);
        if ($filter !== null) {
            $filterObject->set($filter, $value);
        }
        if ($filter2 != null) {
            $filterObject->set($filter2, $value2);
        }
        $filterBag->set('all_transactions', $filterObject);

        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Transaction');
        $transactions = $repo->findByAdministrationAndFilter($administration, $filterObject);

        return $this->render('HomefinanceBundle:Transaction:list.html.twig', array(
            'transactions' => $transactions,
            'administration' => $administration,
            'title' => $this->get('translator')->trans('transactions.list.all.title', array(), 'administration'),
            'page' => 'list_all_transactions_by_category',
            'filter' => $filterObject,
            'filterFactory' => $filterFactory,
            'showProcessedFilter' => true,
            'yearFilter' => true,
        ));
    }

    /**
     * @Route("/transactions/by_tag/{year}", defaults={"year"=null}, name="transactions_by_tag")
     * @param Request $request
     * @return string
     */
    public function overviewByTag(Request $request, $year=null) {
        $administration = $this->checkCurrentAdministration(Permission::VIEW);
        if ($year === null) {
            $now = new \DateTime();
            $year = $now->format('Y');
        }

        $dateUtils = $this->get('homefinance.date_utils');
        $transactionManager = $this->get('homefinance.transaction.manager');
        $result = $transactionManager->getTransactionsGroupedByTag($administration, $year);
        $months = $dateUtils->getMonths();

        $allTags = $this->getDoctrine()->getRepository('HomefinanceBundle:Tag')->findByAdministration($administration);

        $pivotTable = array();
        foreach($result as $row) {
            $tag_id = $row['tag_id'];
            if ($tag_id) {
                $pivotTable[$tag_id][$row['month']] = $row['total'];
            }
        }

        return $this->render('HomefinanceBundle:Transaction:by_tag.html.twig', array(
            'pivotTable' => $pivotTable,
            'columns' => $months,
            'rows' => $allTags,
            'years' => $transactionManager->getDistinctYears($administration),
            'year' => $year
        ));
    }

    /**
     * @Route("/transactions/by_category/{year}", defaults={"year"=null}, name="transactions_by_category")
     * @param Request $request
     * @return string
     */
    public function overviewByCategory(Request $request, $year=null) {
        $administration = $this->checkCurrentAdministration(Permission::VIEW);
        if ($year === null) {
            $now = new \DateTime();
            $year = $now->format('Y');
        }

        $dateUtils = $this->get('homefinance.date_utils');
        $transactionManager = $this->get('homefinance.transaction.manager');
        $result = $transactionManager->getTransactionsGroupedByCategory($administration, $year);
        $months = $dateUtils->getMonths();

        $categories = array();
        $cats = $this->getDoctrine()->getRepository('HomefinanceBundle:Category')->getChildrenByAdministration($administration, false);
        foreach($cats as $cat) {
            $categories[$cat->getId()] = $cat;
        }
        $categories[0] = $this->get('translator')->trans('transactions.no_category', array(), 'administration');

        $pivotTable = array();
        foreach($result as $row) {
            $cat_id = $row['category_id'];
            if (!$cat_id) {
                $cat_id = 0;
            }
            $pivotTable[$cat_id][$row['month']] = $row['total'];
        }

src/HomefinanceBundle/Resources/views/Transaction/by_category.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'transactions.by_category.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'transactions.by_category.title'|trans }}
{% endblock %}

{% block form %}

    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ year }} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% for y in years %}
                <li><a href="{{ url('transactions_by_category', { 'year': y}) }}">{{ y }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <table class="table table-striped table-hover table-condensed table-responsive">
        <thead>
        <tr>
            <th></th>
            {% set column_totals = { } %}
            {% for column_key,column in columns %}
                {% set column_totals = column_totals|merge({ ('_'~column_key) : (0) }) %}
                <th class="text-right"><small>{{ column }}</small></th>
            {% endfor %}
            <th class="text-right warning"><small>{{ 'transactions.by_category.total'|trans }}</small></th>
            <th class="text-right warning"><small>{{ 'transactions.by_category.avg'|trans }}</small></th>
        </tr>
        </thead>
        <tbody>
        {% for row_key,row in rows %}
            {% set row_total = 0 %}
            <tr>
                {% if (row_key == 0) %}
                    <td>
                        <a href="{{ url('list_all_transactions_by_category', {'filter': 'year', 'value': year, 'filter2': 'category', 'value2': 'empty', 'reset': true}) }}">
                        <small>{{ row }}</small>
                        </a>
                    </td>
                {% else %}
                    {% if (row.level == 1) %}
                        <th><a href="{{ url('list_all_transactions_by_category', {'filter': 'year', 'value': year, 'filter2': 'category', 'value2': row.slug, 'reset': true}) }}">
                            <small>{{ row.getIndentedTitle() }}</small>
                        </a></th>
                    {% else %}
                        <td><a href="{{ url('list_all_transactions_by_category', {'filter': 'year', 'value': year, 'filter2': 'category', 'value2': row.slug, 'reset': true}) }}">
                            <small>{{ row.getTitle() }}</small>
                        </a></td>
                    {% endif %}
                {% endif %}

                {% for column_key, column in columns %}
                    <td class="text-right">
                    {% if (pivotTable[row_key] is defined and pivotTable[row_key][column_key] is defined) %}
                        {% set row_total = row_total + pivotTable[row_key][column_key]  %}
                        {% set column_total = column_totals['_'~column_key] + pivotTable[row_key][column_key]  %}
                        {% set column_totals = column_totals|merge({ ('_'~column_key) : (column_total) }) %}
                        <small>&euro; {{ pivotTable[row_key][column_key]|number_format(2, ',', '.') }}</small>
                    {% else %}
                        -
                    {% endif %}
                    </td>
                {% endfor %}
                <th class="text-right warning">
                    <small>&euro; {{ row_total|number_format(2, ',', '.') }}</small>
                </th>
                <th class="text-right warning">
                    <small>&euro; {{ (row_total/12)|number_format(2, ',', '.') }}</small>
                </th>
            </tr>
        {% endfor %}
            <tr>
                <th></th>
                {% set row_total = 0 %}
                {% for column_key,column in columns %}
                    {% set row_total = row_total + column_totals['_'~column_key]  %}
                    <th class="text-right"><small>&euro; {{ column_totals['_'~column_key]|number_format(2, ',', '.') }}</small></th>
                {% endfor %}
                <th class="text-right warning">
                    <small>&euro; {{ row_total|number_format(2, ',', '.') }}</small>
                </th>
                <th class="text-right warning">
                    <small>&euro; {{ (row_total/12)|number_format(2, ',', '.') }}</small>
                </th>
            </tr>
        </tbody>
    </table>
{% endblock %}

src/HomefinanceBundle/Resources/views/Transaction/by_tag.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'transactions.by_tag.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'transactions.by_tag.title'|trans }}
{% endblock %}

{% block form %}

    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ year }} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% for y in years %}
                <li><a href="{{ url('transactions_by_tag', { 'year': y}) }}">{{ y }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <table class="table table-striped table-hover table-condensed table-responsive">
        <thead>
        <tr>
            <th></th>
            {% for column_key,column in columns %}
                <th class="text-right"><small>{{ column }}</small></th>
            {% endfor %}
            <th class="text-right warning"><small>{{ 'transactions.by_tag.total'|trans }}</small></th>
            <th class="text-right warning"><small>{{ 'transactions.by_tag.avg'|trans }}</small></th>
        </tr>
        </thead>
        <tbody>
        {% for row_key,row in rows %}
            {% set row_total = 0 %}
            <tr>
                <td>
                    <a href="{{ url('list_all_transactions_by_tag', {'filter': 'year', 'value': year, 'filter2': 'tag', 'value2': row.slug, 'reset': true}) }}">
                        <small>{{ row.name }}</small>
                    </a>
                </td>
                {% for column_key, column in columns %}
                    <td class="text-right">
                    {% if (pivotTable[row.id] is defined and pivotTable[row.id][column_key] is defined) %}
                        {% set row_total = row_total + pivotTable[row.id][column_key]  %}
                        <small>&euro; {{ pivotTable[row.id][column_key]|number_format(2, ',', '.') }}</small>
                    {% else %}
                        -
                    {% endif %}
                    </td>
                {% endfor %}
                <th class="text-right warning">
                    <small>&euro; {{ row_total|number_format(2, ',', '.') }}</small>
                </th>
                <th class="text-right warning">
                    <small>&euro; {{ (row_total/12)|number_format(2, ',', '.') }}</small>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/HomefinanceBundle/Resources/views/Transaction/import.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'transaction.import.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'transaction.import.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Transaction/list.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block form_title %}
    {{ title }}
{% endblock %}

{% block form %}

    <div class="margin-bottom row">
    {% if (yearFilter) %}
    <div class="btn-group col-xs-12 col-md-1">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ filter.get('year') }} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% for y in filterFactory.getYears(administration) %}
                <li><a href="{{ url(page, { 'filter': 'year', 'value': y}) }}">{{ y }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <div class="btn-group col-xs-12 col-md-1">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if (filter.get('month')) %}{{ filterFactory.getMonth(administration, filter.get('month')) }}{% else %}{{ 'transaction.filter.month'|trans }}{% endif %} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% if (filter.get('month')) %}
            <li><a href="{{ url(page, {'filter':'month'}) }}">{{ 'transaction.filter.reset.month'|trans }}</a></li>
            {% endif %}
            {% for m,month in filterFactory.getMonths(administration) %}
                <li><a href="{{ url(page, { 'filter': 'month', 'value': m}) }}">{{ month }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="btn-group col-xs-12 col-md-2">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if (filter.get('category')) %}{{ filterFactory.getCategory(administration, filter.get('category')) }}{% else %}{{ 'transaction.filter.category'|trans }}{% endif %} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% if (filter.get('category')) %}
                <li><a href="{{ url(page, {'filter':'category'}) }}">{{ 'transaction.filter.reset.category'|trans }}</a></li>
            {% endif %}
            <li><a href="{{ url(page, {'filter': 'category', 'value': 'empty'}) }}">{{ 'transaction.filter.no-category'|trans }}</a></li>
            {% for category in filterFactory.getCategories(administration) %}
                <li><a href="{{ url(page, { 'filter': 'category', 'value': category.slug}) }}">{{ category.indentedTitle }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="btn-group col-xs-12 col-md-2">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if (filter.get('tag')) %}{{ filterFactory.getTag(administration, filter.get('tag')) }}{% else %}{{ 'transaction.filter.tag'|trans }}{% endif %} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% if (filter.get('tag')) %}
                <li><a href="{{ url(page, {'filter':'tag'}) }}">{{ 'transaction.filter.reset.tag'|trans }}</a></li>
            {% endif %}
            {% for tag in filterFactory.getTags(administration) %}
                <li><a href="{{ url(page, { 'filter': 'tag', 'value': tag.slug}) }}">{{ tag.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% if (showProcessedFilter) %}
    <div class="btn-group col-xs-12 col-md-2">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if (filter.get('processed') is not null) %}
                {% if filter.get('processed') %}
                    {{ 'transaction.filter.processed.yes'|trans }}
                {% else %}
                    {{ 'transaction.filter.processed.no'|trans }}
                {% endif %}
            {% else %}
                {{ 'transaction.filter.processed'|trans }}
            {% endif %} <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% if (filter.get('processed') is not null) %}
                <li><a href="{{ url(page, {'filter':'processed'}) }}">{{ 'transaction.filter.reset.processed'|trans }}</a></li>
            {% endif %}
            <li><a href="{{ url(page, { 'filter': 'processed', 'value': 1}) }}">{{ 'transaction.filter.processed.yes'|trans }}</a></li>
            <li><a href="{{ url(page, { 'filter': 'processed', 'value': 0}) }}">{{ 'transaction.filter.processed.no'|trans }}</a></li>
        </ul>
    </div>
    {% endif %}
    </div>

    <div class="list-group">
    {% for transaction in transactions %}
        <div class="list-group-item {% if ((loop.index % 2) == 1) %}list-group-item-odd{% else %}list-group-item-even{% endif %} list-group-item-hover">
            <div class="row">
            <div class="col-md-1">
                <strong>{{ transaction.date|date('d M') }}</strong><br />
                {% if (transaction.isProcessed()) %}
                    <span class="label label-success">{{ 'transaction.state.is_processed'|trans() }}</span>
                {% else %}
                    <span class="label label-warning">{{ 'transaction.state.unprocessed'|trans() }}</span>
                {% endif %}
            </div>
            <div class="col-md-1">
                <h4 class="text-right">&euro; {{ transaction.amount|number_format(2, ',', '.') }}</h4>
            </div>
            <div class="col-md-2">
                {% if transaction.category %}{{ transaction.category.indentedTitle }}{% endif %}<br />
                {% for tag in transaction.tags %}
                    <span class="label label-info">{{ tag.name }}</span>
                {% endfor %}
            </div>
            <div class="col-md-1">
                {{ transaction.bankAccount.name }}
            </div>
            <div class="col-md-2">
                <strong>{{ transaction.name }}</strong><br />
                <small>{{ transaction.description }}</small>
            </div>
            <div class="col-md-2">
                {% if (has_access_to_administration(app.user, administration, 'Edit')) %}
                    <a href="{{ url('transaction_edit', {'id': transaction.id, 'redirect': page}) }}" class="btn btn-xs btn-success">
                        <i class="glyphicon glyphicon-pencil"></i>&nbsp; {{ 'transaction.edit'|trans }}
                    </a>
                {% endif %}
            </div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}