src/HomefinanceBundle/Entity/BankAccount.php
<?php

namespace HomefinanceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * BankAccount
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="HomefinanceBundle\Entity\Repository\BankAccountRepository")
 */
class BankAccount
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @Assert\Iban()
     * @ORM\Column(name="iban", type="string", length=255)
     */
    private $iban;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var Administration
     *
     * @Assert\NotNull()
     * @ORM\ManyToOne(targetEntity="Administration")
     * @ORM\JoinColumn(name="administration_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $administration;

    /**
     * @var float
     *
     * @ORM\Column(name="starting_balance", type="float")
     */
    private $starting_balance;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return BankAccount
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set iban
     *
     * @param string $iban
     * @return BankAccount
     */
    public function setIban($iban)
    {
        $this->iban = $iban;

        return $this;
    }

    /**
     * Get iban
     *
     * @return string 
     */
    public function getIban()
    {
        return $this->iban;
    }

    /**
     * Set image
     *
     * You should encode it as base64
     *
     * @param string $image
     * @return BankAccount
     */
    public function setImage($image)
    {
        if ( base64_encode(base64_decode($image, true)) === $image){
            $this->image = $image;
        } else {
            $this->image = base64_encode($image);
        }


        return $this;
    }

    /**
     * Get image
     *
     * @return string 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return Administration
     */
    public function getAdministration() {
        return $this->administration;
    }

    /**
     * @param Administration $administration
     * @return Category
     */
    public function setAdministration(Administration $administration) {
        $this->administration = $administration;
        return $this;
    }

    /**
     * @return float
     */
    public function getStartingBalance() {
        return $this->starting_balance;
    }

    /**
     * @param float $starting_balance
     * @return $this
     */
    public function setStartingBalance($starting_balance) {
        $this->starting_balance = $starting_balance;
        return $this;
    }

    public function getLabel() {
        return $this->name .' ('.$this->iban.')';
    }
}

src/HomefinanceBundle/Administration/Form/AdministrationEdit.php
<?php

namespace HomefinanceBundle\Administration\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdministrationEdit extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array(
                'label' => 'administration.name.label',
            ))
            ->add('save', 'submit', array(
                'label' => 'administration.update.btn-label',
                'attr' => array(
                    'class' => 'btn btn-lg btn-primary',
                ),
            ))
        ;
    }

    public function getName()
    {
        return 'administration_edit';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'HomefinanceBundle\Entity\Administration',
            'translation_domain' => 'administration',
        ));
    }

}

src/HomefinanceBundle/Administration/Form/Category.php
<?php

namespace HomefinanceBundle\Administration\Form;

use HomefinanceBundle\Administration\Manager\CategoryManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Category extends AbstractType
{

    /**
     * @var CategoryManager
     */
    protected $categoryManager;

    public function __construct(CategoryManager $categoryManager)
    {
        $this->categoryManager = $categoryManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('parent', 'entity', array(
                'label' => 'category.parent.label',
                'class' => 'HomefinanceBundle:Category',
                'choice_label' => 'title',
                'choices' => $this->getCategoryParents($builder->getData()),
            ))
            ->add('title', 'text', array(
                'label' => 'category.title.label',
                'required' => true,
            ))
            ->add('type', 'choice', array(
                'choices' => $this->getCategoryTypes(),
                'required' => true,
                'expanded' => true,
                'label' => 'category.type.label',
            ))
            ->add('save', 'submit', array(
                'label' => 'category.update.btn-label',
                'attr' => array(
                    'class' => 'btn btn-lg btn-primary',
                ),
            ))
        ;
    }

    protected function getCategoryParents(\HomefinanceBundle\Entity\Category $category) {
        return $this->categoryManager->allToplevelOrLevelOne();
    }

    protected function getCategoryTypes() {
        $types = \HomefinanceBundle\Category\Type::getAllTypes();
        foreach($types as $type) {
            $return[$type] = $type;
        }
        return $return;
    }

    public function getName()
    {
        return 'category';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'HomefinanceBundle\Entity\Category',
            'translation_domain' => 'administration',
        ));
    }

}

src/HomefinanceBundle/Administration/Form/DataTransformer/TagsTransformer.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */

namespace HomefinanceBundle\Administration\Form\DataTransformer;

use HomefinanceBundle\Administration\Manager\TagManager;
use Symfony\Component\Form\DataTransformerInterface;

class TagsTransformer implements DataTransformerInterface {

    /**
     * @var TagManager
     */
    protected $tagManager;

    public function __construct(TagManager $tagManager) {
        $this->tagManager = $tagManager;
    }

    public function transform($tags) {
        $values = array();
        foreach($tags as $tag) {
            $values[] = $tag->getName();
        }
        return implode(",", $values);
    }

    public function reverseTransform($tags)
    {
        if(is_null($tags) || !$tags) {
            return;
        }

        $values = explode(",", $tags);
        $return = $this->tagManager->loadOrCreateTags($values);
        return $return;
    }

}

src/HomefinanceBundle/Administration/Controller/AdministrationController.php
<?php
/**
 * @author Jaap Jansma (CiviCooP) <jaap.jansma@civicoop.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.html
 */
namespace HomefinanceBundle\Administration\Controller;

use HomefinanceBundle\Entity\BankAccount;
use HomefinanceBundle\Entity\Category;
use HomefinanceBundle\Share\Permission;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use HomefinanceBundle\DefaultController\DefaultController;

class AdministrationController extends DefaultController {

    /**
     * @Route("/switch/{slug}/", name="switch_administration")
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function switchAction(Request $request, $slug) {
        $user = $this->getUser();
        $accessManager = $this->get('homefinance.administration.access_manager');
        $administration = $accessManager->getAdministrationBySlugWithAccess($slug, $user, Permission::VIEW);

        $user->setCurrentAdministration($administration);
        $em = $this->getDoctrine()->getEntityManager();
        $em->persist($user);
        $em->flush();

        return $this->redirect($this->generateUrl('dashboard'));
    }

    /**
     * @Route("/categories", name="categories")
     * @param Request $request
     * @return Response
     */
    public function categoriesAction(Request $request) {
        $user = $this->getUser();
        $manager = $this->get('homefinance.administration.manager');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);

        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Category');
        $categories = $repo->getChildrenByAdministration($administration, false);

        return $this->render('HomefinanceBundle:Administration:categories.html.twig', array(
            'administration' => $administration,
            'categories' => $categories,
            'manager' => $manager,
            'user' => $user,
        ));
    }

    /**
     * @Route("/tags", name="tags")
     * @param Request $request
     * @return Response
     */
    public function tagsAction(Request $request) {
        $user = $this->getUser();
        $manager = $this->get('homefinance.administration.manager');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);

        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:Tag');
        $tags = $repo->findByAdministration($administration);

        return $this->render('HomefinanceBundle:Administration:tags.html.twig', array(
            'administration' => $administration,
            'tags' => $tags,
            'manager' => $manager,
            'user' => $user,
        ));
    }

    /**
     * @Route("/tags/add", name="add_tag")
     *
     * @param Request $request
     * @return Response
     */
    public function addTagAction(Request $request) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);

        $tag = new \HomefinanceBundle\Entity\Tag();
        $tag->setAdministration($administration);
        $form = $this->createForm('tag', $tag);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($tag);
            $em->flush();
            $this->addFlash('success', 'tag.added');

            return $this->redirect($this->generateUrl('tags'));
        }

        return $this->render('HomefinanceBundle:Administration:add_tag.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/tags/{id}/edit", name="edit_tag")
     *
     * @param Request $request
     * @param $id
     * @return Response
     */
    public function editTagAction(Request $request, $id) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository('HomefinanceBundle:Tag');
        $tag = $repo->findOneByIdAndAdministration($administration, $id);
        $form = $this->createForm('tag', $tag);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em->persist($tag);
            $em->flush();
            $this->addFlash('success', 'tag.edited');

            return $this->redirect($this->generateUrl('tags'));
        }

        return $this->render('HomefinanceBundle:Administration:edit_tag.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/tags/{id}/delete", name="delete_tag")
     *
     * @param Request $request
     * @param $id
     * @return Response
     */
    public function deleteTagAction(Request $request, $id) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository('HomefinanceBundle:Tag');
        $tag = $repo->findOneByIdAndAdministration($administration, $id);
        $em->remove($tag);
        $em->flush();

        $this->addFlash('success', 'tag.removed');

        return $this->redirect($this->generateUrl('tags'));
    }

    /**
     * @Route("/categories/add", name="add_category")
     *
     * @param Request $request
     * @return Response
     */
    public function addCategoryAction(Request $request) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);

        $category = new Category();
        $category->setAdministration($administration);
        $form = $this->createForm('category', $category);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $repo = $em->getRepository('HomefinanceBundle:Category');
            $em->persist($category);
            $repo->verify();
            $repo->recover();
            $em->flush();
            $this->addFlash('success', 'category.added');

            return $this->redirect($this->generateUrl('categories'));
        }

        return $this->render('HomefinanceBundle:Administration:add_category.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/categories/{slug}/edit", name="edit_category")
     *
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function editCategoryAction(Request $request, $slug) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository('HomefinanceBundle:Category');
        $category = $repo->findOneBySlugAndAdministration($administration, $slug);
        $form = $this->createForm('category', $category);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $em->persist($category);
            $repo->verify();
            $repo->recover();
            $em->flush();
            $this->addFlash('success', 'category.edited');

            return $this->redirect($this->generateUrl('categories'));
        }

        return $this->render('HomefinanceBundle:Administration:edit_category.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/categories/{slug}/move-up", name="move_category_up")
     *
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function moveCategoryUpAction(Request $request, $slug) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository('HomefinanceBundle:Category');
        $category = $repo->findOneBySlugAndAdministration($administration, $slug);
        $repo->moveUp($category);

        $this->addFlash('success', 'category.moved-up');

        return $this->redirect($this->generateUrl('categories'));
    }

    /**
     * @Route("/categories/{slug}/move-down", name="move_category_down")
     *
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function moveCategoryDownAction(Request $request, $slug) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository('HomefinanceBundle:Category');
        $category = $repo->findOneBySlugAndAdministration($administration, $slug);
        $repo->moveDown($category);

        $this->addFlash('success', 'category.moved-down');

        return $this->redirect($this->generateUrl('categories'));
    }

    /**
     * @Route("/categories/{slug}/delete", name="delete_category")
     *
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function deleteCategoryAction(Request $request, $slug) {
        $administration = $this->checkCurrentAdministration(Permission::FULL_ACCESS);
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository('HomefinanceBundle:Category');
        $category = $repo->findOneBySlugAndAdministration($administration, $slug);
        $repo->removeFromTree($category);

        $this->addFlash('success', 'category.removed');

        return $this->redirect($this->generateUrl('categories'));
    }

    /**
     * @Route("/bankaccounts", name="bank_accounts")
     * @param Request $request
     * @return Response
     */
    public function bankAccountsAction(Request $request) {
        $user = $this->getUser();
        $manager = $this->get('homefinance.administration.manager');
        $administration = $this->checkCurrentAdministration(Permission::EDIT);

        $bankAccountManager = $this->get('homefinance.bankaccount.manager');

        $repo = $this->getDoctrine()->getRepository('HomefinanceBundle:BankAccount');

src/HomefinanceBundle/Resources/views/Administration/add_bank_account.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'bank_account.add.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'bank_account.add.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/add_category.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'category.add.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'category.add.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/add_tag.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'tag.add.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'tag.add.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/bank_accounts.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'manage_bank_accounts.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'manage_bank_accounts.title'|trans }}
{% endblock %}

{% block form %}
    <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th>{{ 'bank_account.iban'|trans  }}</th>
                <th>{{ 'bank_account.name'|trans }}</th>
                <th>{{ 'bank_account.starting_balance'|trans }}</th>
                <th>{{ 'bank_account.balance'|trans }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
                <tr>
                    <td>
                        {{ account.iban }}
                    </td>
                    <td>{{ account.name }}</td>
                    <td>&euro; {{ account.startingBalance|number_format(2, ',', '.') }}</td>
                    <td>&euro; {{ bank_account_manager.getSaldo(account)|number_format(2, ',', '.') }}</td>
                    <td class="text-right">
                        {% if (has_access_to_administration(app.user, administration, 'Full access')) %}
                            <a href="{{ url('edit_bank_account', {'id': account.id}) }}" class="btn btn-xs btn-success">
                                <i class="glyphicon glyphicon-pencil"></i>&nbsp; {{ 'bank_account.edit'|trans }}
                            </a>
                            <a href="{{ url('delete_bank_account', {'id': account.id}) }}" class="btn btn-xs btn-danger" onclick="return confirm('{{ 'bank_account.delete_confirm'|trans }}');">
                                <i class="glyphicon glyphicon-trash"></i>&nbsp; {{ 'bank_account.delete'|trans }}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if (has_access_to_administration(app.user, administration, 'Full access')) %}
        <a class="btn btn-success" href="{{ url('add_bank_account') }}" role="button"><i class="glyphicon glyphicon-plus"></i> {{ 'bank_account.add'|trans() }}</a>
    {% endif %}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/categories.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'manage_categories.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'manage_categories.title'|trans }}
{% endblock %}

{% block form %}
    <table class="table tree table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th>{{ 'category.title'|trans  }}</th>
                <th>{{ 'category.type'|trans }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for cat in categories %}
                <tr class="treegrid-{{ cat.id }} {% if (cat.parent and not cat.isDirectSubOfRoot()) %}treegrid-parent-{{ cat.parent.id }}{% endif %}">
                    <td>
                        {% for i in 1..cat.level %}
                            <span class="treegrid-indent"></span>
                        {% endfor %}
                        <span class="treegrid-expander"></span>
                        {{ cat.title }}
                    </td>
                    <td>{{ cat.type|trans }}</td>
                    <td class="text-right">
                        {% if (has_access_to_administration(app.user, administration, 'Full access')) %}
                            {% if not cat.isFirstSibling() %}
                                <a href="{{ url('move_category_up', {'slug': cat.slug}) }}" class="btn btn-xs btn-default">
                                    <i class="glyphicon glyphicon-arrow-up"></i>
                                </a>
                            {% else %}
                                <span class="no-move-up-down-xs"></span>
                            {% endif %}
                            {% if not cat.isLastSibling() %}
                                <a href="{{ url('move_category_down', {'slug': cat.slug}) }}" class="btn btn-xs btn-default">
                                    <i class="glyphicon glyphicon-arrow-down"></i>
                                </a>
                            {% else %}
                                <span class="no-move-up-down-xs"></span>
                            {% endif %}
                            <a href="{{ url('edit_category', {'slug': cat.slug}) }}" class="btn btn-xs btn-success">
                                <i class="glyphicon glyphicon-pencil"></i>&nbsp; {{ 'category.edit'|trans }}
                            </a>
                            <a href="{{ url('delete_category', {'slug': cat.slug}) }}" class="btn btn-xs btn-danger" onclick="return confirm('{{ 'category.delete_confirm'|trans }}');">
                                <i class="glyphicon glyphicon-trash"></i>&nbsp; {{ 'category.delete'|trans }}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if (has_access_to_administration(app.user, administration, 'Full access')) %}
        <a class="btn btn-success" href="{{ url('add_category') }}" role="button"><i class="glyphicon glyphicon-plus"></i> {{ 'category.add'|trans() }}</a>
    {% endif %}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/edit.html.twig
{% extends 'HomefinanceBundle:layout:account_settings.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'administration.edit.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'administration.edit.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/edit_bank_account.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'bank_account.edit.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'bank_account.edit.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/edit_category.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'category.edit.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'category.edit.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/edit_tag.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'tag.edit.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'tag.edit.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/manager.html.twig
{% extends 'HomefinanceBundle:layout:account_settings.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'manager.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'manager.title'|trans }}
{% endblock %}

{% block form %}
    <table class="table">
        <thead>
            <tr>
                <th>{{ 'administration.name'|trans  }}</th>
                <th>{{ 'administration.access'|trans  }}</th>
                <th>{{ 'administration.owner'|trans  }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for administration in administrations %}
                <tr>
                    <td>{{ administration.name }}</td>
                    <td>{{ manager.determineAccess(administration, app.user)|trans }}</td>
                    <td>{{ administration.owner.name }}</td>
                    <td>
                        {% if (has_access_to_administration(app.user, administration, 'Full access')) %}
                            <a href="{{ url('share_administration', {'slug':administration.slug}) }}" class="btn btn-sm">
                                <i class="glyphicon glyphicon-user"></i>
                                {{ 'administration.share'|trans }}
                            </a>
                            <a href="{{ url('edit_administration', {'slug':administration.slug}) }}" class="btn btn-sm">
                                <i class="glyphicon glyphicon-wrench"></i>
                                {{ 'administration.edit'|trans }}
                            </a>
                            {% if (app.user == administration.owner) %}
                                <a href="{{ url('delete_administration', {'slug':administration.slug}) }}" class="btn btn-sm btn-danger" onclick="return confirm('{{ 'administration.delete_confirm'|trans }}');">
                                    <i class="glyphicon glyphicon-trash"></i>
                                    {{ 'administration.delete'|trans }}
                                </a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ url('new_administration') }}" role="button"><i class="glyphicon glyphicon-plus"></i> {{ 'administration.add'|trans() }}</a>


{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/new_share.html.twig
{% extends 'HomefinanceBundle:layout:administration.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'share.add.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'share.add.title'|trans }}
{% endblock %}

src/HomefinanceBundle/Resources/views/Administration/shares.html.twig
{% extends 'HomefinanceBundle:layout:account_settings.html.twig' %}

{% trans_default_domain "administration" %}

{% block title %}
    {{ 'administration.shares.title'|trans }}
{% endblock %}

{% block form_title %}
    {{ 'administration.shares.title'|trans }}
{% endblock %}

{% block form %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>{{ 'administration.share.user'|trans  }}</th>
                <th>{{ 'administration.share.access'|trans  }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for share in administration.shares %}
                <tr>
                    <td>
                        <img src="{{ share.user.avatar|imagine_filter('small_profile_picture') }}" alt="{{ share.user.name }}" class="img-circle" />
                        &nbsp;
                        {{ share.user.name }}
                    </td>
                    <td>{{ manager.determineAccess(share.administration, share.user)|trans }}</td>
                    <td>
                        {% if (has_access_to_administration(app.user, administration, 'Full access') and app.user != share.user) %}
                            <a class="btn btn-danger btn-sm" href="{{ url('share_administration_revoke', {
                                'slug': administration.slug,
                                'id': share.id
                            }) }}">
                                <i class="glyphicon glyphicon-trash"></i>&nbsp; {{ 'share.revoke'|trans }}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if (has_access_to_administration(app.user, administration, 'Full access')) %}
        <a class="btn btn-success" href="{{ url('share_administration_add', {'slug': administration.slug}) }}" role="button"><i class="glyphicon glyphicon-plus"></i> {{ 'share.add'|trans() }}</a>
    {% endif %}
{% endblock %}